# This is a basic workflow to help you get started with Actions

name: ci-tests

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: ci for test
      run: echo 'hello world!'
      
    - name: Change file
      run: ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@main
      
    - name: Change file
      run: ls -la
      
    - name: Run tests 
      run: pytest -s -v
